Generate auction id
openprocurement/openprocurement.auction.insider pull request #79
Opened 2019-04-05 13:47 UTC by OrysiaDrabych

2019-04-05 13:49 UTC, oleksiyVeretiuk approved these changes

2019-04-05 13:50 UTC, oleksiyVeretiuk approved these changes

2019-04-09 09:32 UTC, Scandie requested changes
Ті ж зауваження, що і в [цьому ПРі](https://github.com/openprocurement/openprocurement.auction.worker/pull/40)

2019-04-12 13:41 UTC, Scandie approved these changes

2019-04-15 13:09 UTC, merged